# Generated by Django 3.0.8 on 2020-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0002_auto_20200715_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
