# Generated by Django 3.0.8 on 2020-08-21 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0003_auto_20200716_1908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('-date_posted',)},
        ),
    ]
